ReDoS :gift:
grisufrj/old_blog_grisufrj.github.io pull request #3
Opened 2018-06-03 23:55 UTC by MatheusAvellar

2018-06-04 00:03 UTC, jvitor03 commented
Limita o tamanho do post na página principal usando <!-- more -->, automaticamente será adicionado um "Ver mais...", isso melhora a visiblidade do blog. Se eu não to enganando, fullview é false por padrão, mas vc pode explicitar usando fullview: false no header do seu post.

2018-06-04 00:04 UTC, jvitor03 submitted a review, later dismissed
fullview: true

2018-06-04 00:06 UTC, jvitor03 requested changes
Use <!--more--> pra limitar o tamanho do seu texto na página principal do blog isso melhora a visibilidade dos outros posts, no local que você usar esse comentário aparecerá um "ver mais..". Também explicite a propriedade fullview: false no header do seu post, acho que é o padrão, mas não tenho certeza.

2023-08-18 12:35 UTC, es0j approved these changes

2023-08-18 12:36 UTC, es0j commented
Foi mal, atrasamos

2023-08-18 12:36 UTC, merged